---
version: 1

kind: experiment

environment:
  resources:
    cpu:
      requests: 4
      limits: 4
    memory:
      requests: 8000
      limits: 10000
    gpu:
      limits: 1

build:
  image: tensorflow/tensorflow:1.13.1-gpu-py3
  build_steps:
  - pip install --no-cache-dir -U polyaxon-cli

declarations:
  batch_size: 32
  epochs: 30
  log_steps: 100
  max_time: 8h
  learning_rate: 0.01
  learning_rate_decay: 0.92
  model: Mobile
  optimizer: sgd

#hptuning:
#  concurrency: 2
#  matrix:
#    model_type:
#      values: [Mobile, Nasnet, Alex]


run:
  cmd:
  - python src/main.py train --database RafD --data /data/common/RaFD --model {{ model }} --log_steps {{ log_steps }} --batch_size {{ batch_size }} --epochs {{ epochs }} --max_time {{ max_time }} --learning_rate {{ learning_rate }} --learning_rate_decay {{ learning_rate_decay }} --optimizer {{ optimizer }}
  - python src/main.py test --database RafD --data /data/common/RaFD --model {{ model }}
